---
- name: create directory
  file: path=/etc/ansible/kavi1 state=directory mode=775 owner=root group=root

- name: create file
  file: path=/etc/ansible/kavi1/demo.txt state=touch

- name: copy content
  copy: content="Hello kaviya \n" dest=/etc/ansible/kavi1/demo.txt

- name: using array
  debug:
    msg: "{{ name[1] }}"

- name: Command to list files
  shell: ls -lrt > demo.txt

- name: latest version of the required package to be installed
  yum:
    name: firewalld
    state: latest

- name: enabled and running
  service:
    name: firewalld
    state: started
